export const allExpencess=[
    {
        "user_name":"mustak",
        "date":"12/08/18",
        "item":"rice",
        "price":42
    },
    {
        "user_name":"mustak",
        "date":"14/08/18",
        "item":"curry",
        "price":20
    },
    {
        "user_name":"Aziz",
        "date":"03/08/18",
        "item":"rice",
        "price":42
    },
    {
        "user_name":"muzaffer",
        "date":"12/08/18",
        "item":"rice",
        "price":42
    },
    {
        "user_name":"mujaffer",
        "date":"12/08/18",
        "item":"banana",
        "price":20
    },
    {
        "user_name":"aziz",
        "date":"12/08/18",
        "item":"sweet",
        "price":80
    },
    {
        "user_name":"mustak",
        "date":"12/08/18",
        "item":"rice",
        "price":42
    },
    {
        "user_name":"mustak",
        "date":"12/08/18",
        "item":"rice",
        "price":42
    }
]

